include .env
export

BLUE = \033[1;34m
GREEN = \033[1;32m
YELLOW = \033[1;33m
CYAN = \033[36m
RESET = \033[0m

define print_separator
	@printf '%*s\n' "$$(tput cols)" '' | tr ' ' '═'
endef

define start_task
	@echo ""
	$(call print_separator)
	@echo "$(BLUE)$(1)$(RESET)"
	$(call print_separator)
endef

define end_task
	@echo ""
	@echo "$(GREEN)$(1)$(RESET)"
	@echo ""
endef

STORAGES = docker/{{project_slug}}/storages.yaml
APPS = docker/{{project_slug}}/apps.yaml
{%- if database == "postgresql" %}
STORAGE_CON = {{project_slug}}_psql
{%- else %}
STORAGE_CON = {{project_slug}}_mysql
{%- endif %}
DC = docker compose
WEB_CON = {{project_slug}}_web
MANAGE = uv run python manage.py
PRECOMMIT = uv run pre-commit

.PHONY: generate-secret-key
generate-secret-key:
	$(call start_task,Generating SECRET_KEY...)
	uv run python scripts/generate_secret_key.py

.PHONY: pre-commit-check
pre-commit-check:
	$(call start_task,Running pre-commit hooks...)
	$(PRECOMMIT) run --all-files --show-diff-on-failure

.PHONY: build-app
build-app:
	$(call start_task,Building application containers...)
	$(DC) -f $(APPS) build

.PHONY: up-app
up-app:
	$(call start_task,Starting application containers...)
	$(DC) -f $(APPS) up -d

.PHONY: up-storages
up-storages:
	$(call start_task,Starting storage containers...)
	$(DC) -f $(STORAGES) up -d --remove-orphans

.PHONY: logs
logs:
	$(call start_task,Viewing application logs...)
	$(DC) -f $(APPS) logs -f

.PHONY: migrate
migrate:
	$(call start_task,Running database migrations...)
	$(DC) -f $(APPS) exec $(WEB_CON) $(MANAGE) migrate

.PHONY: clean-db
clean-db:
	$(call start_task,Cleaning database volumes...)
	$(DC) -f $(APPS) down
	$(DC) -f $(STORAGES) down -v
	docker volume prune -f

.PHONY: dj-shell
dj-shell:
	$(call start_task,Enter to django shell...)
	$(DC) -f $(APPS) exec $(WEB_CON) $(MANAGE) shell -v 2

.PHONY: db-shell
db-shell:
	$(call start_task,Connecting to database shell...)
{%- if database == "postgresql" %}
	$(DC) -f $(STORAGES) exec $(STORAGE_CON) psql -U $$POSTGRES_USER -d $$POSTGRES_DB
{%- else %}
	$(DC) -f $(STORAGES) exec $(STORAGE_CON) mysql -u $$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE
{%- endif %}

.PHONY: test
test:
	$(call start_task,Running tests in container...)
	$(DC) -f $(APPS) exec $(WEB_CON) uv run pytest

.PHONY: mypy
mypy:
	$(call start_task,Running mypy type checks in container...)
	$(DC) -f $(APPS) exec $(WEB_CON) uv run mypy .

.PHONY: rebuild
rebuild: clean-db generate-secret-key build-app up-storages up-app migrate mypy test
	$(call end_task,Project rebuilt successfully!)

.PHONY: project
project: generate-secret-key build-app up-storages up-app migrate mypy test
	$(call end_task,Project built successfully!)
